export const consultationTypes = {
  FETCH_CONSULTATION_SUCCESS: 'FETCH_CONSULTATION_SUCCESS',
  FETCH_CONSULTATION_LIST_SUCCESS: 'FETCH_CONSULTATION_LIST_SUCCESS',
};

export const consultationPostTypes = {
  FETCH_CONSULTATION_POSTS_SUCCESS: 'FETCH_CONSULTATION_POSTS_SUCCESS',
};

export const sessionTypes = {
  SET_SESSION: 'SET_SESSION',
  FLUSH_SESSION: 'FLUSH_SESSION',
  FETCH_LOGIN: 'FETCH_LOGIN',
  FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
  FETCH_LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',
};

export const loginErrorTypes = {
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  FLUSH_LOGIN_ERROR: 'FLUSH_LOGIN_ERROR',
};
