export const userTypes = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_USER: 'SET_USER',
  UPDATE_USER: 'UPDATE_USER',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
};

export const consultationTypes = {
  FETCH_CONSULTATIONS: 'FETCH_CONSULTATIONS',
  FETCH_CONSULTATIONS_SUCCESS: 'FETCH_CONSULTATIONS_SUCCESS',
};

export const consultationPostTypes = {
  FETCH_CONSULTATION_POSTS_SUCCESS: 'FETCH_CONSULTATION_POSTS_SUCCESS',
};

export const sessionTypes = {
  SET_SESSION: 'SET_SESSION',
  FLUSH_SESSION: 'FLUSH_SESSION',
};

export const loginErrorTypes = {
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  FLUSH_LOGIN_ERROR: 'FLUSH_LOGIN_ERROR',
};
