export const villageTypes = {
  FETCH_VILLAGE: 'FETCH_VILLAGE',
  FETCH_VILLAGE_SUCCESS: 'FETCH_VILLAGE_SUCCESS',
  FETCH_VILLAGE_FAILURE: 'FETCH_CADRES_FAILURE',
};

export const subDistrictTypes = {
  FETCH_SUB_DISTRICT: 'FETCH_SUB_DISTRICT',
  FETCH_SUB_DISTRICT_SUCCESS: 'FETCH_SUB_DISTRICT_SUCCESS',
  FETCH_SUB_DISTRICT_FAILURE: 'FETCH_SUB_DISTRICT_FAILURE',
};

export const districtTypes = {
  FETCH_DISTRICT: 'FETCH_DISTRICT',
  FETCH_DISTRICT_SUCCESS: 'FETCH_DISTRICT_SUCCESS',
  FETCH_DISTRICT_FAILURE: 'FETCH_DISTRICT_FAILURE',
};

export const provinceTypes = {
  FETCH_PROVINCE: 'FETCH_PROVINCE',
  FETCH_PROVINCE_SUCCESS: 'FETCH_PROVINCE_SUCCESS',
  FETCH_PROVINCE_FAILURE: 'FETCH_PROVINCE_FAILURE',
};
